### ISSUE TITLE
[task]:移植网络请求相关代码

### ISSUE THREAD

**Issue by hughdazz** [hughdazz/PPTCopilot#4]
![图片](https://user-images.githubusercontent.com/73471341/231141635-250698a8-b0f6-4f2b-abf7-6fc7d06d443a.png)

在master分支的基础上，将dev分支的图中代码，检查bug并移植到新开分支的src/util中
要求文件名axiosRequest.ts

**Comment by hughdazz** [comment]
注意该文件就是向外提供一些网络请求接口

**Comment by Nekotoxin** [comment]
接
