### ISSUE TITLE
[task]:update_xml_to_dom_to_slide

### ISSUE THREAD

**Issue by hughdazz** [hughdazz/PPTCopilot#6]
![图片](https://user-images.githubusercontent.com/73471341/231143190-a75ee0cb-23ed-4ad1-b9ca-975eaba76948.png)

在master分支的基础上，移植图示中函数，移植代码文件名hooks/useXml2Slide.ts
参数:gpt返回的xml,目前slide
返回:更新的slide

**Comment by onecat233** [comment]
dd.周末前搞完
